version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/TelegramBot

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: chmod +x gradlew

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests and jacoco coverage report
      - run: ./gradlew clean build jacocoTestReport

      # run pitest report
      - run: ./gradlew pitest

      # copy artifacts to dir
      - run:
          name: Copy artifacts
          command: |
            mkdir /tmp/artifacts
            mkdir /tmp/artifacts/jar
            mkdir /tmp/artifacts/test-reports
            cp -r build/libs/* /tmp/artifacts/jar
            cp -r build/reports/* /tmp/artifacts/test-reports

      # store artifacts
      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: build/test-results/test

      # upload coverage on codecov
      - run:
          name: Upload codecov
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success